"""create day18 initial tables

Revision ID: ba594bf836bf
Revises: 
Create Date: 2026-07-15 16:44:53.474432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba594bf836bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_name', sa.String(length=32), nullable=False),
    sa.Column('provider_location_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.String(length=64), nullable=False),
    sa.Column('longitude', sa.String(length=64), nullable=False),
    sa.Column('adm1', sa.String(length=128), nullable=True),
    sa.Column('adm2', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('utc_offset', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'provider_location_id', name='uq_provider_location')
    )
    op.create_index(op.f('ix_locations_provider_location_id'), 'locations', ['provider_location_id'], unique=False)
    op.create_index(op.f('ix_locations_provider_name'), 'locations', ['provider_name'], unique=False)
    op.create_table('task_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('task_date', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.String(length=32), nullable=False),
    sa.Column('end_time', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('raw_request_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_requests_request_id'), 'task_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_task_requests_request_type'), 'task_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_task_requests_task_type'), 'task_requests', ['task_type'], unique=False)
    op.create_table('cruise_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('allow_cruise', sa.Boolean(), nullable=False),
    sa.Column('overall_decision', sa.String(length=32), nullable=False),
    sa.Column('summary_risk_factors_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruise_assessments_location_id'), 'cruise_assessments', ['location_id'], unique=False)
    op.create_index(op.f('ix_cruise_assessments_overall_decision'), 'cruise_assessments', ['overall_decision'], unique=False)
    op.create_index(op.f('ix_cruise_assessments_request_id'), 'cruise_assessments', ['request_id'], unique=False)
    op.create_table('weather_provider_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=32), nullable=False),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('provider_endpoint', sa.String(length=255), nullable=False),
    sa.Column('provider_update_time', sa.String(length=64), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_provider_snapshots_location_id'), 'weather_provider_snapshots', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_provider_snapshots_provider_name'), 'weather_provider_snapshots', ['provider_name'], unique=False)
    op.create_index(op.f('ix_weather_provider_snapshots_request_id'), 'weather_provider_snapshots', ['request_id'], unique=False)
    op.create_index(op.f('ix_weather_provider_snapshots_snapshot_type'), 'weather_provider_snapshots', ['snapshot_type'], unique=False)
    op.create_table('weather_hourly_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('provider_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.String(length=64), nullable=True),
    sa.Column('fx_time', sa.String(length=64), nullable=False),
    sa.Column('temp', sa.String(length=32), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.Column('wind_scale', sa.String(length=32), nullable=True),
    sa.Column('wind_speed', sa.String(length=32), nullable=True),
    sa.Column('humidity', sa.String(length=32), nullable=True),
    sa.Column('precip', sa.String(length=32), nullable=True),
    sa.Column('pop', sa.String(length=32), nullable=True),
    sa.Column('pressure', sa.String(length=32), nullable=True),
    sa.Column('cloud', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['provider_snapshot_id'], ['weather_provider_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_hourly_request_location_fx_time', 'weather_hourly_snapshots', ['request_id', 'location_id', 'fx_time'], unique=False)
    op.create_index(op.f('ix_weather_hourly_snapshots_fx_time'), 'weather_hourly_snapshots', ['fx_time'], unique=False)
    op.create_index(op.f('ix_weather_hourly_snapshots_location_id'), 'weather_hourly_snapshots', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_hourly_snapshots_request_id'), 'weather_hourly_snapshots', ['request_id'], unique=False)
    op.create_table('weather_warning_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('provider_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('warning_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('warning_level', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.Column('publish_time', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.String(length=64), nullable=True),
    sa.Column('end_time', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['provider_snapshot_id'], ['weather_provider_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_warning_snapshots_location_id'), 'weather_warning_snapshots', ['location_id'], unique=False)
    op.create_index(op.f('ix_weather_warning_snapshots_request_id'), 'weather_warning_snapshots', ['request_id'], unique=False)
    op.create_table('cruise_hourly_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('fx_time', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('risk_factors_json', sa.JSON(), nullable=False),
    sa.Column('weather_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['cruise_assessments.id'], ),
    sa.ForeignKeyConstraint(['weather_snapshot_id'], ['weather_hourly_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruise_hourly_assessments_assessment_id'), 'cruise_hourly_assessments', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_cruise_hourly_assessments_decision'), 'cruise_hourly_assessments', ['decision'], unique=False)
    op.create_index(op.f('ix_cruise_hourly_assessments_fx_time'), 'cruise_hourly_assessments', ['fx_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cruise_hourly_assessments_fx_time'), table_name='cruise_hourly_assessments')
    op.drop_index(op.f('ix_cruise_hourly_assessments_decision'), table_name='cruise_hourly_assessments')
    op.drop_index(op.f('ix_cruise_hourly_assessments_assessment_id'), table_name='cruise_hourly_assessments')
    op.drop_table('cruise_hourly_assessments')
    op.drop_index(op.f('ix_weather_warning_snapshots_request_id'), table_name='weather_warning_snapshots')
    op.drop_index(op.f('ix_weather_warning_snapshots_location_id'), table_name='weather_warning_snapshots')
    op.drop_table('weather_warning_snapshots')
    op.drop_index(op.f('ix_weather_hourly_snapshots_request_id'), table_name='weather_hourly_snapshots')
    op.drop_index(op.f('ix_weather_hourly_snapshots_location_id'), table_name='weather_hourly_snapshots')
    op.drop_index(op.f('ix_weather_hourly_snapshots_fx_time'), table_name='weather_hourly_snapshots')
    op.drop_index('ix_weather_hourly_request_location_fx_time', table_name='weather_hourly_snapshots')
    op.drop_table('weather_hourly_snapshots')
    op.drop_index(op.f('ix_weather_provider_snapshots_snapshot_type'), table_name='weather_provider_snapshots')
    op.drop_index(op.f('ix_weather_provider_snapshots_request_id'), table_name='weather_provider_snapshots')
    op.drop_index(op.f('ix_weather_provider_snapshots_provider_name'), table_name='weather_provider_snapshots')
    op.drop_index(op.f('ix_weather_provider_snapshots_location_id'), table_name='weather_provider_snapshots')
    op.drop_table('weather_provider_snapshots')
    op.drop_index(op.f('ix_cruise_assessments_request_id'), table_name='cruise_assessments')
    op.drop_index(op.f('ix_cruise_assessments_overall_decision'), table_name='cruise_assessments')
    op.drop_index(op.f('ix_cruise_assessments_location_id'), table_name='cruise_assessments')
    op.drop_table('cruise_assessments')
    op.drop_index(op.f('ix_task_requests_task_type'), table_name='task_requests')
    op.drop_index(op.f('ix_task_requests_request_type'), table_name='task_requests')
    op.drop_index(op.f('ix_task_requests_request_id'), table_name='task_requests')
    op.drop_table('task_requests')
    op.drop_index(op.f('ix_locations_provider_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_provider_location_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
